apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager
spec:
  ports:
    - port: 6123
      targetPort: 6123
      name: flink
    - port: 50101
      targetPort: 50101
      name: blobserver
  selector:
    app: flink
    component: jobmanager