apiVersion: v1
kind: ReplicationController
metadata:
  name: flink-taskmanager
  namespace: flink
spec:
  replicas: 2
  selector:
    component: taskmanager
  template:
    metadata:
      labels:
        app: flink
        component: taskmanager
    spec:
      containers:
      - name: taskmanager
        image: jene/flink:latest
        args: ["taskmanager", "jobmanager.rpc.address=jobmanager.flink.svc.cluster.local", "blob.server.port=50101"]
        ports:
          - containerPort: 6121
          - containerPort: 6122
          - containerPort: 50101
        resources:
          requests:
            cpu: 100m